### ISSUE TITLE
common.nim: Undeclared identifier 'f'

### ISSUE THREAD

**Issue by mantielero** [ThomasTJdev/nimlibxlsxwriter#3]
It complains about:
```
/home/jose/.nimble/pkgs/nimlibxlsxwriter-0.1.3/nimlibxlsxwriter/common.nim(33, 17) Error: undeclared identifier: 'f'
```

My `common.nim` file contains:
```nim
const
  LXW_MD5_SIZE* = 16
  LXW_SHEETNAME_MAX* = 31
  LXW_EPOCH_1900* = 0
  LXW_EPOCH_1904* = 1
  LXW_FILENAME_LENGTH* = 128
  LXW_IGNORE* = 1
  LXW_PORTRAIT* = 1
  LXW_LANDSCAPE* = 0
  LXW_PRINTF* = f                        # <------- ERROR
```
I seems to be linked to [this](https://github.com/jmcnamara/libxlsxwriter/blob/b45ba65a06ba22fc59d96cd34c7d5d8491c7aa8f/include/xlsxwriter/common.h#L232):
```c
#define LXW_PRINTF fprintf
```

**Comment by mantielero** [comment]
I have just tested that commenting that line passes all tests. So probably it is not used at all.

I have tried this, but I don't get the expected result:
```ini
[include/xlsxwriter/common.h]
search.v = "#define LXW_PRINTF fprintf"
comment.v = 1
```

**Comment by ThomasTJdev** [comment]
> I have just tested that commenting that line passes all tests. So probably it is not used at all.
> 
> I have tried this, but I don't get the expected result:
> 
> ```ini
> [include/xlsxwriter/common.h]
> search.v = "#define LXW_PRINTF fprintf"
> comment.v = 1
> ```

Hi @mantielero 

You need to specify the corresponding nim-code to comment out. The section needs to be like this:
```
[common.nim]
search.tr = "import nimlibxlsxwriter/tree"
append.tr = """

import hash_table
export hash_table.lxw_hash_table
from format import lxw_format
"""

search.v = "LXW_PRINTF* = f"
comment.v = 1
```

I have tested the above and it's working with nim-devel. The test now "only" fails with `chart_data_tools.nim` on `chart_series_set_error_bars`.

**Comment by ThomasTJdev** [comment]
Full code available here: https://github.com/ThomasTJdev/nimlibxlsxwriter/pull/4
